apiVersion: apps/v1
kind: Deployment
metadata:
  name: Mon-deployment
spec:
  selector:
    matchLabels:
      run: Mon-deployment
  replicas: 2
  template:
    metadata:
      labels:
        run: Mon-deployment
    spec:
      containers:
      - name: Mon-deployment
        image: monikayadav007/javademoapp_#JOB-NAME#:#BUILD-NUMBER#
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: Mon-deployment
  labels:
    run: Mon-deployment
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: Mon-deployment
